version: '3.6'
services:
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/01.databases_init.sql:/docker-entrypoint-initdb.d/01.databases_init.sql
      - ./postgres/02.inventory_script.sh:/docker-entrypoint-initdb.d/02.inventory_script.sh
      - ./postgres/03.eventstore_script.sh:/docker-entrypoint-initdb.d/02.docker_eventstore_script.sh
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres